//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 5.3.47.1261
//     Runtime Version: 4.0.30319.18047
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace SampleWebAPIWinFormsPascal.Properties;

interface

type
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute('Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator', '11.0.0.0')]
    Settings = partial sealed class(System.Configuration.ApplicationSettingsBase)
    private 
        class var defaultInstance: Settings := (System.Configuration.ApplicationSettingsBase.Synchronized(new Settings()) as Settings);
        class method get_Default: Settings;
        method get_APIKey: System.String;
        method get_APISecret: System.String;
        method get_RedirectURI: System.String;
        method get_Environment: System.String;
        method get_Interval: System.Int32;
    public 
        class property &Default: Settings read get_Default;
        [System.Configuration.ApplicationScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('your key goes here')]
        property APIKey: System.String read get_APIKey;
        [System.Configuration.ApplicationScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('your secret goes here')]
        property APISecret: System.String read get_APISecret;
        [System.Configuration.ApplicationScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('your redirect URI goes here')]
        property RedirectURI: System.String read get_RedirectURI;
        [System.Configuration.ApplicationScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('Can be "SIM" or "LIVE"')]
        property Environment: System.String read get_Environment;
        [System.Configuration.ApplicationScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute(System.String('5'))]
        property Interval: System.Int32 read get_Interval;
    end;
    
implementation

{ Settings }

class method Settings.get_Default: Settings;
begin
    exit(defaultInstance);
end;

method Settings.get_APIKey: System.String;
begin
    exit((self['APIKey'] as System.String));
end;

method Settings.get_APISecret: System.String;
begin
    exit((self['APISecret'] as System.String));
end;

method Settings.get_RedirectURI: System.String;
begin
    exit((self['RedirectURI'] as System.String));
end;

method Settings.get_Environment: System.String;
begin
    exit((self['Environment'] as System.String));
end;

method Settings.get_Interval: System.Int32;
begin
    exit((self['Interval'] as System.Int32));
end;

end.
